[[dependency]]
org = "ballerina"
name = "os"
version = "1.0.0"

[[dependency]]
org = "ballerina"
name = "log"
version = "2.0.0"

[[dependency]]
org = "ballerina"
name = "url"
version = "2.0.0"

[[dependency]]
org = "ballerina"
name = "random"
version = "1.0.0"

[[dependency]]
org = "ballerina"
name = "time"
version = "2.0.0"

[[dependency]]
org = "ballerina"
name = "http"
version = "2.0.0"

[[dependency]]
org = "ballerina"
name = "jballerina.java.arrays"
version = "1.0.0"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "2.0.0"

[[dependency]]
org = "ballerina"
name = "io"
version = "1.0.0"