name: Dev/Staging BCentral Release

on:
  workflow_dispatch:
    inputs:
      bal_central_environment:
        description: Ballerina Central Environment
        type: choice
        options:
        - STAGE
        - DEV
        required: true

jobs:
    release:

        runs-on: ubuntu-latest
        env: 
          BALLERINA_${{ github.event.inputs.bal_central_environment }}_CENTRAL: true
        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@master
              with:
                  args:
                      pack ./sqs
              env:
                  ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
                  SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
                  REGION: ${{ secrets.REGION }}
                  
            - name: Push to Staging
              if: github.event.inputs.bal_central_environment == 'STAGE'
              uses: ballerina-platform/ballerina-action/@master
              with:
                  args:
                      push
              env:
                  WORKING_DIR: ./sqs
                  BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_STAGE_ACCESS_TOKEN }}
                  
            - name: Push to Dev
              if: github.event.inputs.bal_central_environment == 'DEV'
              uses: ballerina-platform/ballerina-action/@master
              with:
                  args:
                      push
              env:
                  WORKING_DIR: ./sqs
                  BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_DEV_ACCESS_TOKEN }}
